"""Shared, versioned contracts for authorship-attribution components."""

from .calibration import calibrate_cosine, check_baseline_compat
from .contracts import (
    AccountProfile,
    BaselineConfig,
    BaselineDistribution,
    Chunk,
    ComparisonAssets,
    ComparisonReport,
    EmbeddingModel,
    EngineEvaluation,
    EngineResult,
    EvaluationConfig,
    EvaluationReport,
    IngestConfig,
    LabeledPair,
    Message,
    NormalizedStreamChunk,
    PairCounts,
    PreprocessConfig,
    RawStreamChunk,
    RunConfig,
    SemanticConfig,
    StylometryArtifact,
    StylometryConfig,
    message_key,
)
from .errors import ContractValidationError, ErrorCode, error_code_for
from .fileformats import (
    TermList,
    load_labeled_pairs,
    load_term_list,
    read_json_artifact,
    write_json_artifact,
)
from .fingerprints import (
    NORMALIZATION_SPEC_VERSION,
    canonical_json,
    fingerprint,
    preprocessing_fingerprint,
    semantic_fingerprint,
    sha256_hex,
    stylometry_fingerprint,
)

__all__ = [
    "AccountProfile",
    "BaselineConfig",
    "BaselineDistribution",
    "Chunk",
    "ComparisonAssets",
    "ComparisonReport",
    "ContractValidationError",
    "EmbeddingModel",
    "EngineEvaluation",
    "EngineResult",
    "ErrorCode",
    "EvaluationConfig",
    "EvaluationReport",
    "IngestConfig",
    "LabeledPair",
    "Message",
    "NORMALIZATION_SPEC_VERSION",
    "NormalizedStreamChunk",
    "PairCounts",
    "PreprocessConfig",
    "RawStreamChunk",
    "RunConfig",
    "SemanticConfig",
    "StylometryArtifact",
    "StylometryConfig",
    "TermList",
    "calibrate_cosine",
    "canonical_json",
    "check_baseline_compat",
    "error_code_for",
    "fingerprint",
    "load_labeled_pairs",
    "load_term_list",
    "message_key",
    "preprocessing_fingerprint",
    "read_json_artifact",
    "semantic_fingerprint",
    "sha256_hex",
    "stylometry_fingerprint",
    "write_json_artifact",
]
